### ISSUE TITLE
建议：新增单个插件选择备份

### ISSUE THREAD

**Issue by wwg135** [Ketty0725/Tweak_Tool#2]
建议：新增单个插件选择备份

**Comment by Ketty0725** [comment]
> 建议：新增单个插件选择备份

这样的可行？
![image](https://github.com/Ketty0725/Tweak_Tool/assets/103920238/4305a1c7-2617-490c-9d72-02172626e46b)
![image](https://github.com/Ketty0725/Tweak_Tool/assets/103920238/990a02ad-08fb-4e95-a734-d33a1421b029)

**Comment by wwg135** [comment]
> > 建议：新增单个插件选择备份
> 
> 这样的可行？ ![image](https://private-user-images.githubusercontent.com/103920238/313638552-4305a1c7-2617-490c-9d72-02172626e46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NTUyLTQzMDVhMWM3LTI2MTctNDkwYy05ZDcyLTAyMTcyNjI2ZTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmE4ZjRmMWQ3MjI2MzViMjg1OTA4NmM5NDY4NzE2ZTcyNWE1ZTI5MWI2ZTJmOWFlMTdmNzc5YWUwZmRkZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqfX91w3ywUpdGBJWam_fcqVww24BtTbQaWNb-MQuK8) ![image](https://private-user-images.githubusercontent.com/103920238/313638617-990a02ad-08fb-4e95-a734-d33a1421b029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NjE3LTk5MGEwMmFkLTA4ZmItNGU5NS1hNzM0LWQzM2ExNDIxYjAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2RmYTA0ZWY4ODAzZGFmNTIyNDRkNjE1YjY2ZDRkZDU0ZmZiYjdiOWJjMWUzZmE1MDNiMjI4NjhlZGU5N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I3E7ZX6lX0lAhJ3jHATqXbIbVTa-1gNHEgCiWMVjusE)

大佬，这是不错，可以发我测试一下吗？我也是写写代码的

**Comment by Ketty0725** [comment]
> > > 建议：新增单个插件选择备份
> 
> > 
> 
> > 这样的可行？ ![image](https://private-user-images.githubusercontent.com/103920238/313638552-4305a1c7-2617-490c-9d72-02172626e46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NTUyLTQzMDVhMWM3LTI2MTctNDkwYy05ZDcyLTAyMTcyNjI2ZTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmE4ZjRmMWQ3MjI2MzViMjg1OTA4NmM5NDY4NzE2ZTcyNWE1ZTI5MWI2ZTJmOWFlMTdmNzc5YWUwZmRkZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqfX91w3ywUpdGBJWam_fcqVww24BtTbQaWNb-MQuK8) ![image](https://private-user-images.githubusercontent.com/103920238/313638617-990a02ad-08fb-4e95-a734-d33a1421b029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NjE3LTk5MGEwMmFkLTA4ZmItNGU5NS1hNzM0LWQzM2ExNDIxYjAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2RmYTA0ZWY4ODAzZGFmNTIyNDRkNjE1YjY2ZDRkZDU0ZmZiYjdiOWJjMWUzZmE1MDNiMjI4NjhlZGU5N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I3E7ZX6lX0lAhJ3jHATqXbIbVTa-1gNHEgCiWMVjusE)
> 
> 
> 
> 大佬，这是不错，可以发我测试一下吗？我也是写写代码的

已更新到源，这版是以1.4.0为基础的，如果暂时还需要之前1.5.0的先下载deb后再更新吧

**Comment by wwg135** [comment]
> > > > 建议：新增单个插件选择备份
> > 
> > 
> > > 
> > 
> > 
> > > 这样的可行？ ![image](https://private-user-images.githubusercontent.com/103920238/313638552-4305a1c7-2617-490c-9d72-02172626e46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NTUyLTQzMDVhMWM3LTI2MTctNDkwYy05ZDcyLTAyMTcyNjI2ZTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmE4ZjRmMWQ3MjI2MzViMjg1OTA4NmM5NDY4NzE2ZTcyNWE1ZTI5MWI2ZTJmOWFlMTdmNzc5YWUwZmRkZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqfX91w3ywUpdGBJWam_fcqVww24BtTbQaWNb-MQuK8) ![image](https://private-user-images.githubusercontent.com/103920238/313638617-990a02ad-08fb-4e95-a734-d33a1421b029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTk2OTYsIm5iZiI6MTcxMDc1OTM5NiwicGF0aCI6Ii8xMDM5MjAyMzgvMzEzNjM4NjE3LTk5MGEwMmFkLTA4ZmItNGU5NS1hNzM0LWQzM2ExNDIxYjAyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2RmYTA0ZWY4ODAzZGFmNTIyNDRkNjE1YjY2ZDRkZDU0ZmZiYjdiOWJjMWUzZmE1MDNiMjI4NjhlZGU5N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I3E7ZX6lX0lAhJ3jHATqXbIbVTa-1gNHEgCiWMVjusE)
> > 
> > 
> > 大佬，这是不错，可以发我测试一下吗？我也是写写代码的
> 
> 已更新到源，这版是以1.4.0为基础的，如果暂时还需要之前1.5.0的先下载deb后再更新吧

大佬牛逼，谢谢！
