### ISSUE TITLE
建议备份的deb文件名字用插件名称来命名

### ISSUE THREAD

**Issue by ardenyang** [Ketty0725/Tweak_Tool#3]
首先感谢大佬开发这么好的工具，让重新越狱后的恢复变得非常简单和快速。

提个建议：记得1.4版本的时候备份的deb文件是用插件的名字来命名的，看起来很清楚。但到了1.5及1.6版本的备份的deb文件似乎是用包名来命名的，名字有点长，而且看起来不像之前那样清楚。
![image](https://github.com/Ketty0725/Tweak_Tool/assets/63284262/f41e1e0f-2c1b-4587-be67-15bcd5726c5d)

![image](https://github.com/Ketty0725/Tweak_Tool/assets/63284262/deaff561-8457-47ac-ba07-1174c30655ee)

**Comment by Ketty0725** [comment]
> 首先感谢大佬开发这么好的工具，让重新越狱后的恢复变得非常简单和快速。
> 
> 提个建议：记得1.4版本的时候备份的deb文件是用插件的名字来命名的，看起来很清楚。但到了1.5及1.6版本的备份的deb文件似乎是用包名来命名的，名字有点长，而且看起来不像之前那样清楚。
> ![image](https://github.com/Ketty0725/Tweak_Tool/assets/63284262/f41e1e0f-2c1b-4587-be67-15bcd5726c5d)
> 
> ![image](https://github.com/Ketty0725/Tweak_Tool/assets/63284262/deaff561-8457-47ac-ba07-1174c30655ee)

因为name可能会有重复，如果有重复，打包时会因为重名，其中一个包会将另一个包给覆盖了，比如com.dao.safarix和com.dao.safarix.cn，一个插件本体，一个中文包，查询出来的name都是Safari X，打包最后只剩其中一个，之后我再看看有没有好的解决办法，解决了我会加回来的

**Comment by ardenyang** [comment]
明白了，感谢🙏🏻

**Comment by ardenyang** [comment]
文件名以name开头，跟上包名和版本号，是否就能避免文件覆盖的问题

**Comment by Ketty0725** [comment]
> 文件名以name开头，跟上包名和版本号，是否就能避免文件覆盖的问题

我刚才重新研究了一下，解决了

**Comment by Ketty0725** [comment]
请刷新源更新至1.6.2版本
![image](https://github.com/Ketty0725/Tweak_Tool/assets/103920238/5baf6c88-ee7b-4291-820a-2e11277d83a7)
![image](https://github.com/Ketty0725/Tweak_Tool/assets/103920238/eb2d1feb-d73e-4038-9ae6-de2557fd2e87)

**Comment by ardenyang** [comment]
已更新并验证，文件名看起来清晰很多，感谢大佬快速解决。
